spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: myGroup #consumer group id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      #value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      #properties:
         #spring.json.trusted.packages:  '*'   #'com.dev.anh.kafka.payload' # If the serialization is only done by a trusted source, you can also enable trust all (*).

server:
  port:
    8081